if(MSVC)
    if(${MSVC_VERSION} EQUAL 1800)
        install (FILES "${CMAKE_CURRENT_LIST_DIR}/../openssl/winxp_x86/libeay32.dll" DESTINATION "./" OPTIONAL)
        install (FILES "${CMAKE_CURRENT_LIST_DIR}/../openssl/winxp_x86/ssleay32.dll" DESTINATION "./" OPTIONAL)
    else()
        if(CMAKE_SYSTEM_PROCESSOR STREQUAL "x86")
            install (FILES "${CMAKE_CURRENT_LIST_DIR}/../openssl/win_x86/libcrypto-1_1.dll" DESTINATION "./" OPTIONAL)
            install (FILES "${CMAKE_CURRENT_LIST_DIR}/../openssl/win_x86/libssl-1_1.dll" DESTINATION "./" OPTIONAL)
        elseif(CMAKE_SYSTEM_PROCESSOR STREQUAL "AMD64")
            install (FILES "${CMAKE_CURRENT_LIST_DIR}/../openssl/win_x64/libcrypto-1_1-x64.dll" DESTINATION "./" OPTIONAL)
            install (FILES "${CMAKE_CURRENT_LIST_DIR}/../openssl/win_x64/libssl-1_1-x64.dll" DESTINATION "./" OPTIONAL)
        endif()
    endif()
endif()
