function(deploy_init)
    set(X_PROJECT_ARCH "x86")

    # x86 architecture detection
    if("${CMAKE_SYSTEM_PROCESSOR}" STREQUAL "AMD64" OR "${CMAKE_SYSTEM_PROCESSOR}" STREQUAL "x86_64")
        set(X_PROJECT_ARCH "amd64")
    elseif("${CMAKE_SYSTEM_PROCESSOR}" MATCHES "i[3-6]86" OR "${CMAKE_SYSTEM_PROCESSOR}" STREQUAL "x86")
        set(X_PROJECT_ARCH "x86")

    # ARM architecture detection
    elseif("${CMAKE_SYSTEM_PROCESSOR}" MATCHES "^arm" OR "${CMAKE_SYSTEM_PROCESSOR}" MATCHES "armv[0-9]")
        set(X_PROJECT_ARCH "arm")
    elseif("${CMAKE_SYSTEM_PROCESSOR}" STREQUAL "aarch64" OR "${CMAKE_SYSTEM_PROCESSOR}" STREQUAL "arm64")
        set(X_PROJECT_ARCH "arm64")

    # Other common architectures
    elseif("${CMAKE_SYSTEM_PROCESSOR}" MATCHES "^(powerpc|ppc)64")
        set(X_PROJECT_ARCH "ppc64")
    elseif("${CMAKE_SYSTEM_PROCESSOR}" MATCHES "^(powerpc|ppc)")
        set(X_PROJECT_ARCH "ppc")
    elseif("${CMAKE_SYSTEM_PROCESSOR}" MATCHES "mips")
        set(X_PROJECT_ARCH "mips")
    elseif("${CMAKE_SYSTEM_PROCESSOR}" MATCHES "riscv")
        if("${CMAKE_SYSTEM_PROCESSOR}" MATCHES "64")
            set(X_PROJECT_ARCH "riscv64")
        else()
            set(X_PROJECT_ARCH "riscv32")
        endif()
    else()
        message(WARNING "Unknown architecture: ${CMAKE_SYSTEM_PROCESSOR}")
        set(X_PROJECT_ARCH "${CMAKE_SYSTEM_PROCESSOR}")
    endif()

    message(STATUS X_PROJECT_ARCH: ${X_PROJECT_ARCH})

    if (WIN32)
        if (CMAKE_SIZEOF_VOID_P EQUAL 8)
            set(X_PROJECT_OSNAME "win64")
        else()
            set(X_PROJECT_OSNAME "win32")
        endif()

        if(MSVC)
            if(${MSVC_VERSION} EQUAL 1800)
                set(X_PROJECT_OSNAME "winxp")
                set(X_PROJECT_ARCH "x86")
            endif()
        endif()
    endif()
    if (CMAKE_SYSTEM_NAME MATCHES "Linux")
        execute_process (
            COMMAND bash -c ". /etc/os-release; echo -n $NAME"
            OUTPUT_VARIABLE X_OS_NAME
        )
        execute_process (
            COMMAND bash -c ". /etc/os-release; echo -n $VERSION_ID"
            OUTPUT_VARIABLE X_OS_VERSION
        )

        set(X_PROJECT_OSNAME ${X_OS_NAME}_${X_OS_VERSION})
        message(STATUS X_OS_NAME: ${X_OS_NAME})
        message(STATUS X_OS_VERSION: ${X_OS_VERSION})
        message(STATUS X_PROJECT_OSNAME: ${X_PROJECT_OSNAME})

        if (EXISTS "/etc/debian_version")
            file (STRINGS "/etc/debian_version" X_DEBIAN_VERSION)
            message(STATUS "X_DEBIAN_VERSION: ${X_DEBIAN_VERSION}")
            if (X_DEBIAN_VERSION MATCHES "squeeze")
                set(X_DEBIAN_VERSION "6")
            elseif (X_DEBIAN_VERSION MATCHES "squeeze")
                set(X_DEBIAN_VERSION "7")
            elseif (X_DEBIAN_VERSION MATCHES "squeeze")
                set(X_DEBIAN_VERSION "8")
            elseif (X_DEBIAN_VERSION MATCHES "squeeze")
                set(X_DEBIAN_VERSION "9")
            elseif (X_DEBIAN_VERSION MATCHES "squeeze")
                set(X_DEBIAN_VERSION "10")
            elseif (X_DEBIAN_VERSION MATCHES "squeeze")
                set(X_DEBIAN_VERSION "11")
            elseif (X_DEBIAN_VERSION MATCHES "bookworm")
                set(X_DEBIAN_VERSION "12")
            else()
                set(X_DEBIAN_VERSION "11")
            endif()

            set(X_DEBIAN_VERSION ${X_DEBIAN_VERSION})

            message(STATUS "X_DEBIAN_VERSION: ${X_DEBIAN_VERSION}")
            message(STATUS "CMAKE_SYSTEM_NAME: ${CMAKE_SYSTEM_NAME}")
        endif()
    endif()

    if(APPLE)
        set (CMAKE_OSX_ARCHITECTURES x86_64) # TODO make option
        add_compile_options(-Wno-deprecated-declarations)
        add_compile_options(-Wno-switch)
    endif()

    #set(CPACK_SOURCE_GENERATOR "ZIP")
    set(CPACK_INCLUDE_TOPLEVEL_DIRECTORY OFF)
    set(CPACK_OUTPUT_FILE_PREFIX packages)
    set(CPACK_RESOURCE_FILE_LICENSE "${PROJECT_SOURCE_DIR}/../LICENSE")
    set(CPACK_RESOURCE_FILE_README "${PROJECT_SOURCE_DIR}/../README.md")
    file (STRINGS "${PROJECT_SOURCE_DIR}/../release_version.txt" CPACK_PACKAGE_VERSION)
    set(CPACK_PACKAGE_NAME ${X_PROJECTNAME})
    set(CPACK_PACKAGE_INSTALL_DIRECTORY ${X_PROJECTNAME})
    set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY ${X_PROJECTNAME})
    set(CPACK_PACKAGE_VENDOR ${X_COMPANYNAME})
    set(CPACK_PACKAGE_DESCRIPTION ${X_DESCRIPTION})
    set(CPACK_PACKAGE_HOMEPAGE_URL ${X_HOMEPAGE})

    if (CMAKE_SYSTEM_NAME MATCHES "Linux")
        set(CPACK_DEBIAN_PACKAGE_MAINTAINER ${X_MAINTAINER})
        set(CPACK_PACKAGE_FILE_NAME "${CPACK_PACKAGE_NAME}_${CPACK_PACKAGE_VERSION}_${X_PROJECT_OSNAME}_${X_PROJECT_ARCH}")
        message(STATUS CPACK_DEBIAN_PACKAGE_NAME: ${CPACK_DEBIAN_PACKAGE_NAME})
        #set(CPACK_DEBIAN_PACKAGE_SECTION ${X_SECTION})
    endif()

    if (WIN32)
        set(CPACK_PACKAGE_FILE_NAME "${CPACK_PACKAGE_NAME}_${X_PROJECT_OSNAME}_portable_${CPACK_PACKAGE_VERSION}")
    endif()

    if (CMAKE_SYSTEM_NAME MATCHES "Linux")
        # Qt5
        if (NOT "${Qt5Core_VERSION}" STREQUAL "")
            if (X_DEBIAN_VERSION LESS 11)
                list(APPEND X_DEBIAN_PACKAGE_DEPENDS "qt5-default")
            endif()
            list(APPEND X_DEBIAN_PACKAGE_DEPENDS "libqt5core5a")
            list(APPEND X_DEBIAN_PACKAGE_DEPENDS "libqt5dbus5") # TODO Check
        endif()
        if (NOT "${Qt5Gui_VERSION}" STREQUAL "")
            list(APPEND X_DEBIAN_PACKAGE_DEPENDS "libqt5gui5")
        endif()
        if (NOT "${Qt5Widgets_VERSION}" STREQUAL "")
            list(APPEND X_DEBIAN_PACKAGE_DEPENDS "libqt5widgets5")
        endif()
        if (NOT "${Qt5Svg_VERSION}" STREQUAL "")
            list(APPEND X_DEBIAN_PACKAGE_DEPENDS "libqt5svg5")
        endif()
        if (NOT "${Qt5Sql_VERSION}" STREQUAL "")
            list(APPEND X_DEBIAN_PACKAGE_DEPENDS "libqt5sql5")
        endif()
        if (NOT "${Qt5OpenGL_VERSION}" STREQUAL "")
            list(APPEND X_DEBIAN_PACKAGE_DEPENDS "libqt5opengl5")
        endif()
        if (NOT "${Qt5Network_VERSION}" STREQUAL "")
            list(APPEND X_DEBIAN_PACKAGE_DEPENDS "libqt5network5")
        endif()
        if (NOT "${Qt5Script_VERSION}" STREQUAL "")
            list(APPEND X_DEBIAN_PACKAGE_DEPENDS "libqt5script5")
        endif()
        if (NOT "${Qt5ScriptTools_VERSION}" STREQUAL "")
            list(APPEND X_DEBIAN_PACKAGE_DEPENDS "libqt5scripttools5")
        endif()
        # Qt6
        if (NOT "${Qt6Core_VERSION}" STREQUAL "")
            list(APPEND X_DEBIAN_PACKAGE_DEPENDS "libqt6core6")
        endif()
        if (NOT "${Qt6Gui_VERSION}" STREQUAL "")
            list(APPEND X_DEBIAN_PACKAGE_DEPENDS "libqt6gui6")
        endif()
        if (NOT "${Qt6Widgets_VERSION}" STREQUAL "")
            list(APPEND X_DEBIAN_PACKAGE_DEPENDS "libqt6widgets6")
        endif()
        if (NOT "${Qt6Sql_VERSION}" STREQUAL "")
            list(APPEND X_DEBIAN_PACKAGE_DEPENDS "libqt6sql6")
        endif()
        if (NOT "${Qt6Network_VERSION}" STREQUAL "")
            list(APPEND X_DEBIAN_PACKAGE_DEPENDS "libqt6network6")
        endif()

        string(REPLACE ";" ", " CPACK_DEBIAN_PACKAGE_DEPENDS "${X_DEBIAN_PACKAGE_DEPENDS}")
        message(STATUS CPACK_DEBIAN_PACKAGE_DEPENDS: ${CPACK_DEBIAN_PACKAGE_DEPENDS})
    endif()

    include(CPack)

    if(WIN32)
        configure_file("${PROJECT_SOURCE_DIR}/../res/resource.rc.in" "${PROJECT_SOURCE_DIR}/../res/resource.rc" @ONLY)
    endif()

   # get_cmake_property(_variableNames VARIABLES)
   # list (SORT _variableNames)
   # foreach (_variableName ${_variableNames})
   #     message(STATUS "${_variableName}=${${_variableName}}")
   # endforeach()

   # foreach(loopVAR IN LISTS PROJECT_SOURCES)
   #    message("Source from a PROJECT_SOURCES: ${loopVAR}")
   #    set_property(SOURCE ${loopVAR} PROPERTY COMPILE_OPTIONS ${a_FLAGS})
   # endforeach()

endfunction()

function(deploy_msvc)
    set(options)
    set(oneValueArgs DESTINATION)
    set(multiValueArgs)
    cmake_parse_arguments(DEPLOY "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

    if(NOT DEPLOY_DESTINATION)
        set(DEPLOY_DESTINATION "./")
    endif()

    message(STATUS ${MSVC_TOOLSET_VERSION})
    if(MSVC)
        # Discover runtime paths, then only install the explicit allowlist.
        set(CMAKE_INSTALL_SYSTEM_RUNTIME_DESTINATION "${DEPLOY_DESTINATION}")
        set(CMAKE_INSTALL_UCRT_LIBRARIES TRUE)
        set(CMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP TRUE)
        include(InstallRequiredSystemLibraries)

        if(CMAKE_INSTALL_SYSTEM_RUNTIME_LIBS)
            foreach(_runtime_lib ${CMAKE_INSTALL_SYSTEM_RUNTIME_LIBS})
                get_filename_component(_runtime_name "${_runtime_lib}" NAME)

                if(_runtime_name STREQUAL "msvcp140.dll"
                    OR _runtime_name STREQUAL "msvcp140_1.dll"
                    OR _runtime_name STREQUAL "msvcp140_2.dll"
                    OR _runtime_name STREQUAL "vcruntime140.dll"
                    OR _runtime_name STREQUAL "vcruntime140_1.dll")
                    install(FILES "${_runtime_lib}" DESTINATION "${DEPLOY_DESTINATION}" OPTIONAL)
                endif()
            endforeach()
        else()
            message(WARNING "MSVC runtime libraries were not discovered by InstallRequiredSystemLibraries.")
        endif()
    endif()
endfunction()

function(deploy_qt)
    message(STATUS qt_version_${QT_VERSION_MAJOR})
    if (WIN32)
        if (NOT "${CMAKE_PREFIX_PATH}" STREQUAL "")
            string(REPLACE "\\" "/" CMAKE_PREFIX_PATH ${CMAKE_PREFIX_PATH})
        endif()
        # Qt5
        if (NOT "${Qt5Core_VERSION}" STREQUAL "")
            install (FILES "${CMAKE_PREFIX_PATH}/bin/Qt5Core.dll" DESTINATION "./" OPTIONAL)
        endif()
        if (NOT "${Qt5Gui_VERSION}" STREQUAL "")
            install (FILES "${CMAKE_PREFIX_PATH}/bin/Qt5Gui.dll" DESTINATION "./" OPTIONAL)
            install (FILES "${CMAKE_PREFIX_PATH}/plugins/platforms/qwindows.dll" DESTINATION platforms OPTIONAL)
            install (FILES "${CMAKE_PREFIX_PATH}/plugins/imageformats/qjpeg.dll" DESTINATION imageformats OPTIONAL)
            install (FILES "${CMAKE_PREFIX_PATH}/plugins/imageformats/qtiff.dll" DESTINATION imageformats OPTIONAL)
            install (FILES "${CMAKE_PREFIX_PATH}/plugins/imageformats/qico.dll" DESTINATION imageformats OPTIONAL)
            install (FILES "${CMAKE_PREFIX_PATH}/plugins/imageformats/qgif.dll" DESTINATION imageformats OPTIONAL)
        endif()
        if (NOT "${Qt5Widgets_VERSION}" STREQUAL "")
            install (FILES "${CMAKE_PREFIX_PATH}/bin/Qt5Widgets.dll" DESTINATION "./" OPTIONAL)
        endif()
        if (NOT "${Qt5OpenGL_VERSION}" STREQUAL "")
            install (FILES "${CMAKE_PREFIX_PATH}/bin/Qt5OpenGL.dll" DESTINATION "./" OPTIONAL)
        endif()
        if (NOT "${Qt5Svg_VERSION}" STREQUAL "")
            install (FILES "${CMAKE_PREFIX_PATH}/bin/Qt5Svg.dll" DESTINATION "./" OPTIONAL)
        endif()
        if (NOT "${Qt5Sql_VERSION}" STREQUAL "")
            install (FILES "${CMAKE_PREFIX_PATH}/bin/Qt5Sql.dll" DESTINATION "./" OPTIONAL)
            install (FILES "${CMAKE_PREFIX_PATH}/plugins/sqldrivers/qsqlite.dll" DESTINATION sqldrivers OPTIONAL)
        endif()
        if (NOT "${Qt5Network_VERSION}" STREQUAL "")
            install (FILES "${CMAKE_PREFIX_PATH}/bin/Qt5Network.dll" DESTINATION "./" OPTIONAL)
        endif()
        if (NOT "${Qt5Script_VERSION}" STREQUAL "")
            install (FILES "${CMAKE_PREFIX_PATH}/bin/Qt5Script.dll" DESTINATION "./" OPTIONAL)
        endif()
        if (NOT "${Qt5ScriptTools_VERSION}" STREQUAL "")
            install (FILES "${CMAKE_PREFIX_PATH}/bin/Qt5ScriptTools.dll" DESTINATION "./" OPTIONAL)
        endif()
        #Qt6
        if (NOT "${Qt6Core_VERSION}" STREQUAL "")
            install (FILES "${CMAKE_PREFIX_PATH}/bin/Qt6Core.dll" DESTINATION "./" OPTIONAL)
        endif()
        if (NOT "${Qt6Gui_VERSION}" STREQUAL "")
            install (FILES "${CMAKE_PREFIX_PATH}/bin/Qt6Gui.dll" DESTINATION "./" OPTIONAL)
            install (FILES "${CMAKE_PREFIX_PATH}/plugins/platforms/qwindows.dll" DESTINATION platforms OPTIONAL)
            install (FILES "${CMAKE_PREFIX_PATH}/plugins/imageformats/qjpeg.dll" DESTINATION imageformats OPTIONAL)
            install (FILES "${CMAKE_PREFIX_PATH}/plugins/imageformats/qsvg.dll" DESTINATION imageformats OPTIONAL)
            install (FILES "${CMAKE_PREFIX_PATH}/plugins/imageformats/qico.dll" DESTINATION imageformats OPTIONAL)
            install (FILES "${CMAKE_PREFIX_PATH}/plugins/imageformats/qgif.dll" DESTINATION imageformats OPTIONAL)
        endif()
        if (NOT "${Qt6Widgets_VERSION}" STREQUAL "")
            install (FILES "${CMAKE_PREFIX_PATH}/bin/Qt6Widgets.dll" DESTINATION "./" OPTIONAL)
        endif()
        if (NOT "${Qt6OpenGL_VERSION}" STREQUAL "")
            install (FILES "${CMAKE_PREFIX_PATH}/bin/Qt6OpenGL.dll" DESTINATION "./" OPTIONAL)
        endif()
        if (NOT "${Qt6Svg_VERSION}" STREQUAL "")
            install (FILES "${CMAKE_PREFIX_PATH}/bin/Qt6Svg.dll" DESTINATION "./" OPTIONAL)
        endif()
        if (NOT "${Qt6Sql_VERSION}" STREQUAL "")
            install (FILES "${CMAKE_PREFIX_PATH}/bin/Qt6Sql.dll" DESTINATION "./")
            install (FILES "${CMAKE_PREFIX_PATH}/plugins/sqldrivers/qsqlite.dll" DESTINATION sqldrivers OPTIONAL)
        endif()
        if (NOT "${Qt6Network_VERSION}" STREQUAL "")
            install (FILES "${CMAKE_PREFIX_PATH}/bin/Qt6Network.dll" DESTINATION "./" OPTIONAL)
        endif()
        if (NOT "${Qt6Qml_VERSION}" STREQUAL "")
            install (FILES "${CMAKE_PREFIX_PATH}/bin/Qt6Qml.dll" DESTINATION "./" OPTIONAL)
        endif()
    endif()
endfunction()

function(deploy_configure_cpack_zip)
    set(options)
    set(oneValueArgs NAME VERSION VENDOR INCLUDE_TOPLEVEL_DIRECTORY)
    set(multiValueArgs)
    cmake_parse_arguments(DEPLOY "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

    if(NOT DEPLOY_NAME)
        set(DEPLOY_NAME ${PROJECT_NAME})
    endif()
    if(NOT DEPLOY_VERSION)
        set(DEPLOY_VERSION ${PROJECT_VERSION})
    endif()
    if(NOT DEPLOY_VENDOR)
        set(DEPLOY_VENDOR ${PROJECT_NAME})
    endif()
    if(NOT DEFINED DEPLOY_INCLUDE_TOPLEVEL_DIRECTORY)
        set(DEPLOY_INCLUDE_TOPLEVEL_DIRECTORY ON)
    endif()

    set(CPACK_PACKAGE_NAME "${DEPLOY_NAME}" PARENT_SCOPE)
    set(CPACK_PACKAGE_VENDOR "${DEPLOY_VENDOR}" PARENT_SCOPE)
    set(CPACK_PACKAGE_VERSION "${DEPLOY_VERSION}" PARENT_SCOPE)
    set(CPACK_GENERATOR "ZIP" PARENT_SCOPE)
    set(CPACK_INCLUDE_TOPLEVEL_DIRECTORY "${DEPLOY_INCLUDE_TOPLEVEL_DIRECTORY}" PARENT_SCOPE)
endfunction()

function(deploy_add_windeployqt)
    if(NOT WIN32)
        return()
    endif()

    set(options)
    set(oneValueArgs QT_DIR DESTINATION)
    set(multiValueArgs EXECUTABLES)
    cmake_parse_arguments(DEPLOY "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

    if(NOT DEPLOY_EXECUTABLES)
        message(FATAL_ERROR "deploy_add_windeployqt requires EXECUTABLES.")
    endif()

    if(NOT DEFINED DEPLOY_DESTINATION)
        set(DEPLOY_DESTINATION "bin")
    endif()

    set(_windeployqt "")

    if(DEPLOY_QT_DIR)
        string(REPLACE "\\" "/" _qt_dir "${DEPLOY_QT_DIR}")
        set(_windeployqt_candidate "${_qt_dir}/bin/windeployqt.exe")
        if(EXISTS "${_windeployqt_candidate}")
            set(_windeployqt "${_windeployqt_candidate}")
        endif()
    endif()

    if((NOT _windeployqt) AND CMAKE_PREFIX_PATH)
        set(_qt_prefix_paths ${CMAKE_PREFIX_PATH})
        list(GET _qt_prefix_paths 0 _qt_prefix_first)
        string(REPLACE "\\" "/" _qt_prefix_first "${_qt_prefix_first}")
        set(_windeployqt_candidate "${_qt_prefix_first}/bin/windeployqt.exe")
        if(EXISTS "${_windeployqt_candidate}")
            set(_windeployqt "${_windeployqt_candidate}")
        endif()
    endif()

    if((NOT _windeployqt) AND TARGET Qt6::qmake)
        get_target_property(_qt_qmake_exe Qt6::qmake IMPORTED_LOCATION)
        if(_qt_qmake_exe)
            get_filename_component(_qt_bin_dir "${_qt_qmake_exe}" DIRECTORY)
            find_program(_windeployqt windeployqt HINTS "${_qt_bin_dir}")
        endif()
    endif()

    if((NOT _windeployqt) AND TARGET Qt5::qmake)
        get_target_property(_qt_qmake_exe Qt5::qmake IMPORTED_LOCATION)
        if(_qt_qmake_exe)
            get_filename_component(_qt_bin_dir "${_qt_qmake_exe}" DIRECTORY)
            find_program(_windeployqt windeployqt HINTS "${_qt_bin_dir}")
        endif()
    endif()

    if(NOT _windeployqt)
        find_program(_windeployqt windeployqt)
    endif()

    if(_windeployqt)
        string(REPLACE "\\" "/" _windeployqt "${_windeployqt}")
        set(_deploy_code "set(_windeployqt \"${_windeployqt}\")\n")
        string(APPEND _deploy_code "set(_deploy_dir \"\${CMAKE_INSTALL_PREFIX}\")\n")
        string(APPEND _deploy_code "if(NOT \"${DEPLOY_DESTINATION}\" STREQUAL \"\" AND NOT \"${DEPLOY_DESTINATION}\" STREQUAL \".\")\n")
        string(APPEND _deploy_code "    set(_deploy_dir \"\${CMAKE_INSTALL_PREFIX}/${DEPLOY_DESTINATION}\")\n")
        string(APPEND _deploy_code "endif()\n")
        foreach(_deploy_exe ${DEPLOY_EXECUTABLES})
            string(APPEND _deploy_code "execute_process(\n")
            string(APPEND _deploy_code "    COMMAND \"\${_windeployqt}\" --release --no-compiler-runtime --no-translations --dir \"\${_deploy_dir}\" \"\${_deploy_dir}/${_deploy_exe}\"\n")
            string(APPEND _deploy_code "    RESULT_VARIABLE _deploy_result\n")
            string(APPEND _deploy_code ")\n")
            string(APPEND _deploy_code "if(NOT _deploy_result EQUAL 0)\n")
            string(APPEND _deploy_code "    message(FATAL_ERROR \"windeployqt failed for ${_deploy_exe}\")\n")
            string(APPEND _deploy_code "endif()\n")
        endforeach()

        install(CODE "${_deploy_code}")
    else()
        message(WARNING "windeployqt was not found. Package ZIP will not include Qt runtime DLLs.")
    endif()
endfunction()
