include_directories(${CMAKE_CURRENT_LIST_DIR})

if (NOT DEFINED XSHORTCUTS_SOURCES)
    include(${CMAKE_CURRENT_LIST_DIR}/../XShortcuts/xshortcuts.cmake)
    set(XABOUTWIDGET_SOURCES ${XABOUTWIDGET_SOURCES} ${XSHORTCUTS_SOURCES})
endif()

set(XABOUTWIDGET_SOURCES
    ${XABOUTWIDGET_SOURCES}
    ${CMAKE_CURRENT_LIST_DIR}/xaboutwidget.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xaboutwidget.h
    ${CMAKE_CURRENT_LIST_DIR}/xaboutwidget.ui
)
